/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as OnboardingDiagnosticoRouteImport } from './routes/onboarding.diagnostico'
import { Route as OnboardingComoFuncionaRouteImport } from './routes/onboarding.como-funciona'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppInicioRouteImport } from './routes/app.inicio'
import { Route as AppFinanzasRouteImport } from './routes/app.finanzas'
import { Route as AppAprenderRouteImport } from './routes/app.aprender'
import { Route as AppAprenderIndexRouteImport } from './routes/app.aprender.index'
import { Route as AppAprenderLeccionIdRouteImport } from './routes/app.aprender.leccion.$id'
import { Route as AppAprenderLeccionRouteImport } from './routes/app.aprender.leccion.'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingDiagnosticoRoute = OnboardingDiagnosticoRouteImport.update({
  id: '/onboarding/diagnostico',
  path: '/onboarding/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingComoFuncionaRoute = OnboardingComoFuncionaRouteImport.update({
  id: '/onboarding/como-funciona',
  path: '/onboarding/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppAprenderRoute = AppAprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => AppRoute,
} as any)
const AppAprenderIndexRoute = AppAprenderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAprenderRoute,
} as any)
const AppAprenderLeccionIdRoute = AppAprenderLeccionIdRouteImport.update({
  id: '/leccion/$id',
  path: '/leccion/$id',
  getParentRoute: () => AppAprenderRoute,
} as any)
const AppAprenderLeccionRoute = AppAprenderLeccionRouteImport.update({
  id: '/leccion/',
  path: '/leccion/',
  getParentRoute: () => AppAprenderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/aprender': typeof AppAprenderRouteWithChildren
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/onboarding/como-funciona': typeof OnboardingComoFuncionaRoute
  '/onboarding/diagnostico': typeof OnboardingDiagnosticoRoute
  '/app/': typeof AppIndexRoute
  '/app/aprender/': typeof AppAprenderIndexRoute
  '/app/aprender/leccion/': typeof AppAprenderLeccionRoute
  '/app/aprender/leccion/$id': typeof AppAprenderLeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/onboarding/como-funciona': typeof OnboardingComoFuncionaRoute
  '/onboarding/diagnostico': typeof OnboardingDiagnosticoRoute
  '/app': typeof AppIndexRoute
  '/app/aprender': typeof AppAprenderIndexRoute
  '/app/aprender/leccion': typeof AppAprenderLeccionRoute
  '/app/aprender/leccion/$id': typeof AppAprenderLeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/aprender': typeof AppAprenderRouteWithChildren
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/inicio': typeof AppInicioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/onboarding/como-funciona': typeof OnboardingComoFuncionaRoute
  '/onboarding/diagnostico': typeof OnboardingDiagnosticoRoute
  '/app/': typeof AppIndexRoute
  '/app/aprender/': typeof AppAprenderIndexRoute
  '/app/aprender/leccion/': typeof AppAprenderLeccionRoute
  '/app/aprender/leccion/$id': typeof AppAprenderLeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/aprender'
    | '/app/finanzas'
    | '/app/inicio'
    | '/app/perfil'
    | '/onboarding/como-funciona'
    | '/onboarding/diagnostico'
    | '/app/'
    | '/app/aprender/'
    | '/app/aprender/leccion/'
    | '/app/aprender/leccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/finanzas'
    | '/app/inicio'
    | '/app/perfil'
    | '/onboarding/como-funciona'
    | '/onboarding/diagnostico'
    | '/app'
    | '/app/aprender'
    | '/app/aprender/leccion'
    | '/app/aprender/leccion/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/aprender'
    | '/app/finanzas'
    | '/app/inicio'
    | '/app/perfil'
    | '/onboarding/como-funciona'
    | '/onboarding/diagnostico'
    | '/app/'
    | '/app/aprender/'
    | '/app/aprender/leccion/'
    | '/app/aprender/leccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingComoFuncionaRoute: typeof OnboardingComoFuncionaRoute
  OnboardingDiagnosticoRoute: typeof OnboardingDiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/diagnostico': {
      id: '/onboarding/diagnostico'
      path: '/onboarding/diagnostico'
      fullPath: '/onboarding/diagnostico'
      preLoaderRoute: typeof OnboardingDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/como-funciona': {
      id: '/onboarding/como-funciona'
      path: '/onboarding/como-funciona'
      fullPath: '/onboarding/como-funciona'
      preLoaderRoute: typeof OnboardingComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inicio': {
      id: '/app/inicio'
      path: '/inicio'
      fullPath: '/app/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finanzas': {
      id: '/app/finanzas'
      path: '/finanzas'
      fullPath: '/app/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprender': {
      id: '/app/aprender'
      path: '/aprender'
      fullPath: '/app/aprender'
      preLoaderRoute: typeof AppAprenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/aprender/': {
      id: '/app/aprender/'
      path: '/'
      fullPath: '/app/aprender/'
      preLoaderRoute: typeof AppAprenderIndexRouteImport
      parentRoute: typeof AppAprenderRoute
    }
    '/app/aprender/leccion/$id': {
      id: '/app/aprender/leccion/$id'
      path: '/leccion/$id'
      fullPath: '/app/aprender/leccion/$id'
      preLoaderRoute: typeof AppAprenderLeccionIdRouteImport
      parentRoute: typeof AppAprenderRoute
    }
    '/app/aprender/leccion/': {
      id: '/app/aprender/leccion/'
      path: '/leccion'
      fullPath: '/app/aprender/leccion/'
      preLoaderRoute: typeof AppAprenderLeccionRouteImport
      parentRoute: typeof AppAprenderRoute
    }
  }
}

interface AppAprenderRouteChildren {
  AppAprenderIndexRoute: typeof AppAprenderIndexRoute
  AppAprenderLeccionRoute: typeof AppAprenderLeccionRoute
  AppAprenderLeccionIdRoute: typeof AppAprenderLeccionIdRoute
}

const AppAprenderRouteChildren: AppAprenderRouteChildren = {
  AppAprenderIndexRoute: AppAprenderIndexRoute,
  AppAprenderLeccionRoute: AppAprenderLeccionRoute,
  AppAprenderLeccionIdRoute: AppAprenderLeccionIdRoute,
}

const AppAprenderRouteWithChildren = AppAprenderRoute._addFileChildren(
  AppAprenderRouteChildren,
)

interface AppRouteChildren {
  AppAprenderRoute: typeof AppAprenderRouteWithChildren
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppInicioRoute: typeof AppInicioRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAprenderRoute: AppAprenderRouteWithChildren,
  AppFinanzasRoute: AppFinanzasRoute,
  AppInicioRoute: AppInicioRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingComoFuncionaRoute: OnboardingComoFuncionaRoute,
  OnboardingDiagnosticoRoute: OnboardingDiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
